### ISSUE TITLE
V8 code coverage broken when using this runtime

### ISSUE THREAD

**Issue by rene-leanix** [reside-eng/jest-runtime#22]
We're using the `coverageProvider` v8 in Jest 28.1.3 and have full code coverage for our app (for all code that is not ignored specifically), but are also experiencing the devastating memory leak your runtime is fixing. With your runtime enabled, a lot of previously covered lines are suddenly shown as uncovered, including imports and empty lines.

Are you aware of this issue? Would it be worth trying to pull in the latest version of https://github.com/facebook/jest/blob/main/packages/jest-runtime/src/index.ts?

**Comment by a88zach** [comment]
Since this runtime [extends](https://github.com/reside-eng/jest-runtime/blob/main/src/index.js#L10) the default runtime, the package should already be using the latest version of the default runtime depending on what version of jest you are on.

https://github.com/reside-eng/jest-runtime/blob/main/package.json#L22

Have you tried updating to Jest v29?  With Jest v29 you can also now set `workerIdleMemoryLimit` even with runInBand set.  This may be a better alternative if you are tied to using the v8 coverage provider

**Comment by rene-leanix** [comment]
Thanks for the hint! We'll try out `--workerIdleMemoryLimit` as an alternative.
